### ISSUE TITLE
[Feat][Upgradinatorr] Search by Profile

### ISSUE THREAD

**Issue by Drazzilb08** [angrycuban13/Just-A-Bunch-Of-Starr-Scripts#10]
Kind of along the lines of ignore by tag you could also add a `--profile " "` tag and the script will only search that profiles

**Comment by angrycuban13** [comment]
So filter down the movies to any movies with the profile specified?

**Comment by Drazzilb08** [comment]
Correct. Something along the lines of limiting a search by tag.

The use case for me would to search regular movies/shows and not anime. Either having a whitelist or blacklist.

**Comment by angrycuban13** [comment]
One of these days
