### ISSUE TITLE
[Feat][upgradinatorr] ignore specified custom formats

### ISSUE THREAD

**Issue by ahatdude** [angrycuban13/Just-A-Bunch-Of-Starr-Scripts#24]
It'd be nice if somehow we could ignore certain custom formats.
As an example, I've been seeing quite a few movies redownload just because it has that extra point for "freeleech" (as per trash's custom format weights). I'd love to be able to tell the script to ignore that since there's no need to redownload it.
I could just delete that custom format and not update it, but I kind of like to have it for manual downloading.

Thanks!

P.S. I posted this previously in another feature request, but thought this is a simpler way for you to handle requests and not have to dive into threads.

**Comment by angrycuban13** [comment]
This should be fairly easy to add. I can't believe it has ben 27 days since I read this initially...I'll try to get it done this weekend

**Comment by ahatdude** [comment]
If you decide to give it a shot, let me know any way I can help in this (I mean it, not an empty offer).

Have a nice day :-)

**Comment by ahatdude** [comment]
I actually managed to do this by just ignoring some CFs when updating them directly from TraSH's list. It wouldn't be a bad thing to be able to ignore some, however since it seems to complicated I'll let you decide if it's something you'd want to venture into.
Have a nice weekend!
