### ISSUE TITLE
radarr4K block not recognized and tagName not tagged in radarr

### ISSUE THREAD

**Issue by kevindd992002** [angrycuban13/Just-A-Bunch-Of-Starr-Scripts#53]
So I started using your script and I'm running into issues:

1. When I put my 4K radarr instance in the `[Radarr4K]` block of the conf file, it is not being recognized and the script errors out with the URL not being in the correct format. When I transfer the same details to the `[Radarr]` block, your script recognizes the information and successfully triggers the search in radarr.
2. After the search for 10 items is done, I'm expecting it to tag those movies with the word `upgraded` but I cannot see any tags on them in radarr. FWIW, I don't really use tags in radarr. Can that maybe the cause of the issue, because my tags list is empty?

**Comment by bakerboy448** [comment]
> After the search for 10 items is done, I'm expecting it to tag those movies with the word upgraded but I cannot see any tags on them in radarr. FWIW, I don't really use tags in radarr. Can that maybe the cause of the issue, because my tags list is empty?

did you reload/refresh the GUI?  tag api calls do not trigger signalr/ui updates and need a refresh to show / ditto for showing the tags for a movie.

**Comment by kevindd992002** [comment]
Aha! I refreshed the GUI and there they are now. I didn't know that. Thanks!

Script output (verbose): https://gist.github.com/kevindd992002/2420e4e15e4a74e79b4d4de52b918910

Radarr4K block:

```
[Radarr4K]
ApiKey=
Count=10
Monitored=true
MovieStatus=announced
TagName=upgraded
Unattended=false
Url=http://radarr-uhd.home.arpa:7878
```

**Comment by kevindd992002** [comment]
If I have two radarr instances there and specify a value of `radarr` for the `apps` parameter of the script, will it start searching N items for each? Or will it do 5 and 5?

**Comment by kevindd992002** [comment]
> script output shows it handling the Radarr4k just fine and no error as you noted?
> 
> `MovieStatus=announced` strongly advice not using this.....it doesn't make sense to search for any and every movie that simply exists in your radarr even if it is never in theaters or on disk yet.

Sorry for the confusion. The output was when I was using the `[Radarr]` block. Here's the script output for when I use the `[Radarr4K] block:

```

```

Ahh, good point. So when is `announced` even used? In that case, which between `released` and `in cinemas` should I use? I've been using announced from the very beginning.

**Comment by kevindd992002** [comment]
> script output shows it handling the Radarr4k just fine and no error as you noted?
> 
> `MovieStatus=announced` strongly advice not using this.....it doesn't make sense to search for any and every movie that simply exists in your radarr even if it is never in theaters or on disk yet.

Sorry for the confusion. The output was when I was using the `[Radarr]` block. Here's the script output for when I use the `[Radarr4K] block:

```
VERBOSE: Array not detected
VERBOSE: Location for config file is /scripts/Upgradinatorr/upgradinatorr.conf
VERBOSE: Parsing config file
VERBOSE: Config file parsed successfully
Valid application specified
Verbose logging enabled
Exception: /scripts/Upgradinatorr/upgradinatorr.ps1:140
Line |
 140 |          throw "Your URL for $((Get-Culture).TextInfo.ToTitleCase($app …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Your URL for Radarr is not formatted correctly, it must start with
     | http(s)://

```

Ahh, good point. So when is `announced` even used? In that case, which between `released` and `in cinemas` should I use? I've been using announced from the very beginning.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/faq#what-is-minimum-availability

-------

https://github.com/angrycuban13/Just-A-Bunch-Of-Starr-Scripts/blob/28141eb70d2b54b3ec719c947f0df0978e47c3d4/Upgradinatorr/upgradinatorr.ps1#L418

and what app are you passing as the parameter when using [Radarr4k]?   if it's not `radarr4k` then that is presumably the issue.

**Comment by kevindd992002** [comment]
Aha! It's working now. My first try was `Radarr4K` and it didn't recognize it. I tried `radarr4k` now and it's working. I thought they aren't case sensitive because it's powershell.
