### ISSUE TITLE
[Bug][upgradinatorr] Manual Search Early Termination

### ISSUE THREAD

**Issue by zippydude** [angrycuban13/Just-A-Bunch-Of-Starr-Scripts#56]
When running a manual search, such as "upgradinatorr.ps1 -apps radarr,radarr4k,sonarr,sonarr4k", if any app exhausts items to search for, the script will exit instead of continuing to the next app.

Given the above command, if radarr4k runs of out of movies to search, the script will terminate and sonarr and sonarr4k will not have upgrades kicked off.

This issue affects sonarr, radarr, and lidarr instances. The bug occurs here - https://github.com/angrycuban13/Just-A-Bunch-Of-Starr-Scripts/blob/main/Upgradinatorr/upgradinatorr.ps1#L571.

**Comment by angrycuban13** [comment]
Fixed in 0d79818 - thanks for letting me know
