### ISSUE TITLE
[Feat][Upgradinatorr]Discord Webhook Enhancements

### ISSUE THREAD

**Issue by zhdenny** [angrycuban13/Just-A-Bunch-Of-Starr-Scripts#57]
In unattended mode, the Discord Webhook doesn't do anything since it technically never starts/ends.....it just loops.

Regardless of that though, Each time Upgradinatorr runs, can the discord webhook send the list of Shows/Movies it triggered a search on. Just would be a nice sorta summary of what just got triggered to search.

**Comment by Venom84** [comment]
I'd also love to see this. Would be a great addition :-)
