### ISSUE TITLE
Tag required? 

### ISSUE THREAD

**Issue by Shawn9347** [angrycuban13/Just-A-Bunch-Of-Starr-Scripts#59]
I don't want to apply tags. Why would you want that? How can I use this without tags? 

![image](https://user-images.githubusercontent.com/48714886/229277457-f14c7998-de4f-4f4b-996b-67b82cd1e5c3.png)

**Comment by Shawn9347** [comment]
I edited the script.

**Comment by bakerboy448** [comment]
Tags are used and required to avoid searching the same movies over and over again....

**Comment by Shawn9347** [comment]
Yes. And that's exactly what you want for upgrades isn't it?

**Comment by bakerboy448** [comment]
They're tagged after they're searched

**Comment by Shawn9347** [comment]
Yes but what if there's another upgrade maybe a year later or so. Then it won't search that movie every again. You want the same items to be searched multiple times.

**Comment by bakerboy448** [comment]
> Unattended
> Run the script in an infinite loop and search the library forever and ever until the end of the Internet

removes tags and starts over
