### ISSUE TITLE
[Feature Request] Sonarr Mark All Items As Monitored

### ISSUE THREAD

**Issue by methanoid** [angrycuban13/Just-A-Bunch-Of-Starr-Scripts#61]
I have my library but (long story not relevant) lost all my files. I'd "helpfully" marked some series as unmonitored as they had reached ultimate state and I thought this might reduce the load on Sonarr. Now I have thousands of missing items but Sonarr thinks the unmonitored ones aren't to be looked for.  I don't want to mark "Specials" as monitored, just put every item back to the default Monitored status

So its either scan every single TV show looking at status and manually changing to "monitoring" OR... some clever script  ;-)

Pretty please @angrycuban13    (PS I loved Cuba when I visited in 2018)

**Comment by bakerboy448** [comment]
Unmonitored tells the Starrs to ignore this and you don't want this.  It makes no sense for you to mark shows you want as unmonitored

**Comment by methanoid** [comment]
Might want to re-read what I wrote. I KNOW I dont want unmonitored. I also have tried the Mass Editor and marked ALL shows as monitored but it doesnt go into that and mark all seasons as monitored.   

Example, TV show had seasons 4-10 marked as unmonitored cos had reached required standard. When I use Mass Editor all it does is mark the SHOW as monitored. It doesnt mark all files as monitored.

**Comment by bakerboy448** [comment]
> mark all seasons/episodes as monitored

it does.  V3 use season pass to update seasons.  V4 mass editor, update monitoring to update seasons

**Comment by methanoid** [comment]
Thanks, I've never used Season Pass in many years of Sonarr use...  I had no idea. That was VERY helpful :-)
