### ISSUE TITLE
[feat][upgradinatorr] Allow the script to select which indexer(s) to search

### ISSUE THREAD

**Issue by AN1MATEK** [angrycuban13/Just-A-Bunch-Of-Starr-Scripts#68]
Let's start with "I don't know if this is even possible".

**Use case**
You recently joined a new tracker and/or they are doing a global free leech. You want to profit and upgrade your library, but you don't want the search to include other trackers.

**Proposal**
add a `indexer` option in the config, default to `all` but otherwise trackers can be specified.

Thank you for the consideration.

**Comment by bakerboy448** [comment]
Not possible. No such method in starr exists

**Comment by angrycuban13** [comment]
This is not possible with this script. This script is essentially doing the same as you clicking "Search" on the web UI.

**Comment by AN1MATEK** [comment]
My workaround atm is to basically deactivate the other indexers and the click Search all. That's not gonna happen, right? Thanks for the answers.

**Comment by angrycuban13** [comment]
Correct, what you're asking for is outside of the scope of this script.
